nics-dp/petsard

content/docs/usage/10_Evaluator.md

Close #594 
- Fix:
- Try to follow KaTex - f30ef7ff9a0af366cc0a1f5dab25705c69441379

fix: LaTex follow KaTex

---

content/docs/usage/10_Evaluator.md

Close #594 
- Fix
- 3rd attempt for LaTex follow KaTex - a567332ce7f9a56586721ed3841e9c558dac4c6d

fix: 3rd attempt for LaTex follow KaTex

---

content/docs/usage/10_Evaluator.md

Close #594 
- Fix
- 4th attempt for LaTex follow KaTex - 181057999ba78eebbabc4de1e34b53fd40b10e08

fix: 4th attempt for LaTex follow KaTex

---

content/docs/usage/10_Evaluator.md
content/docs/usage/10_Evaluator.zh-tw.md

Close #594 
- Fix
- 5th attempt for LaTex follow KaTex - 19c7bcf4495c637989a093f3c42ed4f2175f0f25

fix: 5th attempt for LaTex follow KaTex

---

content/docs/usage/10_Evaluator.md
content/docs/usage/10_Evaluator.zh-tw.md

Close #594 
- Fix
- 6th attempt for LaTex follow KaTex - 19c36e88613f1d4131ed17450df1de71acd8167c

fix: 6th attempt for LaTex follow KaTex

---

content/docs/usage/10_Evaluator.md
content/docs/usage/10_Evaluator.zh-tw.md

Close #594 
- Fix 
- 7th attempt for LaTex follow KaTex - 289e0852f804b1998afc026aac1d7ca7e2a38873

fix: 7th attempt for LaTex follow KaTex

---

poetry.lock
pyproject.toml

Close #606
- Fix
- update dependency ot tornado - fd7d9c7205f31adc49cf193b93b95f4fbff63b50
---
- https://app.asana.com/0/0/1208972287214036

fix: dependabot alerts no. 19 - tornado gt 642

---

doc_site/content/docs/tutorial/use-cases/custom-evaluation.md
doc_site/content/docs/tutorial/use-cases/custom-evaluation.zh-tw.md

close #681 
- docs
- indent fixation in Custom Evaluation - 823a2bbeb1f914e2e05760effed7bacfc1ed958f
---
- https://app.asana.com/0/0/1209420414760897

docs: indent fixation in Custom Evaluation

---

demo/logging-configuration.ipynb
demo/utils.py
doc_site/content/docs/developer-guide/_index.md
doc_site/content/docs/developer-guide/_index.zh-tw.md
doc_site/content/docs/developer-guide/anonymeter.md
doc_site/content/docs/developer-guide/anonymeter.zh-tw.md
doc_site/content/docs/developer-guide/experiment-name-in-reporter.md
doc_site/content/docs/developer-guide/experiment-name-in-reporter.zh-tw.md
doc_site/content/docs/developer-guide/logging-configuration.md
doc_site/content/docs/developer-guide/logging-configuration.zh-tw.md
doc_site/content/docs/developer-guide/test-coverage.md
doc_site/content/docs/developer-guide/test-coverage.zh-tw.md
petsard/__init__.py
petsard/config.py
petsard/config_base.py
petsard/executor.py
petsard/loader/loader.py
petsard/loader/splitter.py
petsard/synthesizer/synthesizer.py
pyproject.toml
tests/loader/test_loader.py
tests/test_executor.py
yaml/logging-configuration.yaml

close #635 
- feat: customized logging - 010bccbd801f6253f70b4a041e52f0bd592f0d42
- `executor.py`: `_get_config()` to handle `yaml.safe_load()` in `Executor`, `_setup_logger()` to made logger been setting under trace
- `config.py`: get dictionary (without `Executor`) directly
- `config_base.py`, `loader/loader.py` introduce `BaseConfig` class to handle all dataclass config
- fix:
- `pyproject.toml`: version should be 1.1.1
- `loader.py`, `splitter.py`. `synthesizer.py`: not change in #687 
- refactor:
- `__init__.py`, `demo/utils.py`: let `Executor` as the only interface
- docs:
- `logging-configuration.md`, `logging-configuration.zh-tw.md`, `demo/logging-configuration.ipynb`, `yaml/logging-configuration.yaml`: 
- `test-converage.md`, `test-coverage.zh-tw.md`: add `test_executor` related …

feat: customized logging

---

doc_site/content/_index.md
doc_site/content/_index.zh-tw.md
doc_site/content/docs/_index.md
doc_site/content/docs/_index.zh-tw.md

close #701 
- docs: fix photo link
- index(.zh-tw).md
- docs/index(.zh-tw).md
---
- https://app.asana.com/0/0/1209746132065348

docs: fix photo link

---

.github/workflows/trivy-sbom-gen.yml
.github/workflows/trivy-vuln-scan.yml

1. Add a action to generate SBOM on release.
2. Add a action to scan open-source vulnerabilities.

feat(ci): add 2 github actions

---

.github/workflows/trivy-sbom-gen.yml
.github/workflows/trivy-vuln-scan.yml

1. Add a action to generate SBOM on release.
2. Add a action to scan open-source vulnerabilities.

feat(ci): add SBOM on release

---

petsard/evaluator/describer.py
petsard/evaluator/evaluator.py
petsard/evaluator/stats.py
petsard/operator.py

close #750 
- fix: duplicated code caused by merge conflicts - 2d44e018fd06c9d9dcc2129bfe4174cc99cf65d8
- operator.py
- evaluator/
- describer.py
- evaluator.py
- stats.py
---
- https://app.asana.com/0/0/1210108773014993

fix: duplicated code caused by merge conflicts

---

doc_site/content/docs/api/constrainer.md
doc_site/content/docs/api/constrainer.zh-tw.md
petsard/constrainer/nan_group_constrainer.py

close #754 
- feat: add nan_if_condition in nan_group_constrainer - f4933725927c5404cb93ecb421f3483ea84c1bb8
- constrainer/nan_group_constrainer
- docs: add nan_if_condition in nan_group_constrainer 
- doc_site/content/doc/api/constrainter(.zh-tw).md 
---
- https://app.asana.com/0/0/1210174230359777

feat: add nan_if_condition in nan_group_constrainer

---

petsard/loader/loader.py
petsard/loader/metadata.py
petsard/util/dtype_operations.py

close #756 
-  feat:
- completed assign as str when loading with column_types set as category
- loader/loader.py
- loader/metadata.py
- util/dtype_operations.py
---
- https://app.asana.com/0/0/1210174230359789

feat: completed assign as str when loading with column_types set as category

---

petsard/constrainer/constrainer.py
petsard/constrainer/field_combination_constrainer.py
petsard/constrainer/field_constrainer.py
petsard/operator.py
petsard/processor/base.py
petsard/synthesizer/synthesizer.py

close #758 
- fix:
- constraints related effective modification - f14a17a6489e6535a8f3e966da55b2edaacf78e5
- operator.py
- constrainer/constrainer.py
- constrainer/field_constrainer.py
- constrainer/field_combination_constrainer.py
- processor/base.py
- synthesizer/synthesizer.py
---
- https://app.asana.com/0/0/1210174230359803

fix: constraints related effective modification

---

doc_site/content/docs/api/synthesizer.md
doc_site/content/docs/api/synthesizer.zh-tw.md
petsard/loader/loader.py
petsard/processor/base.py
petsard/processor/encoder.py

- fix:
- handle the NA format as expected (`pd.NA`) - d980b5d9c06385933517339d7acc26d1845d76aa
- petsard/loader/loader.py
- specially handle NA in processor - d980b5d9c06385933517339d7acc26d1845d76aa
- petsard/processor/base.py
- petsard/processor/encoder.py
- docs:
- update latest usage of Synthesizer - d980b5d9c06385933517339d7acc26d1845d76aa
- doc_site/content/docs/api/synthesizer(.zh-tw).md
---
- https://app.asana.com/0/0/1210432939912142

fix: handle missing values in encoder

---

.github/workflows/semantic-release.yml
doc_site/content/docs/api/synthesizer.md
doc_site/content/docs/api/synthesizer.zh-tw.md
petsard/loader/loader.py
petsard/metadater/__init__.py
petsard/metadater/datatype.py
petsard/metadater/field_meta.py
petsard/metadater/field_ops.py
petsard/metadater/metadata.py
petsard/metadater/metadata_ops.py
petsard/metadater/metadater.py
petsard/metadater/schema_meta.py
petsard/metadater/schema_ops.py
petsard/processor/base.py
petsard/processor/encoder.py

close #782 
- feat:
- create Metadata - 227a9ccff382237dd0ab1cee20961471628aee29
- petsard/metadater/...
---
- https://app.asana.com/0/0/1209155684179611
- https://app.asana.com/0/0/1210460092812020

feat: replace Metadata and util by Metadater module

---

petsard/reporter/reporter.py

close #794 
- fix(reporter):
- handle non-DataFrame values gracefully in input validation - 20e1aa947c6df59c9c6c7080193228a44b8b7f51
- petsard/reporter/reporter.py
---
- https://app.asana.com/0/0/1210497318893375

fix(reporter): handle non-DataFrame values gracefully in input validation

---

petsard/util/dtype_operations.py

close #796 
- fix(dtype):
- handle NA values in categorical dtype conversion - c95b20e878e730006ba0e26bca362a03acb0c2b0
- petsard/util/dtype_operations.py
---
- https://app.asana.com/0/0/1210497318893389

fix(dtype): handle NA values in categorical dtype conversion

---

doc_site/content/docs/developer-guide/test-coverage.md
doc_site/content/docs/developer-guide/test-coverage.zh-tw.md
petsard/loader/loader.py
petsard/metadater/field/field_functions.py
petsard/metadater/field/field_types.py
petsard/metadater/field/type_inference.py
petsard/metadater/schema/schema_functions.py
petsard/metadater/schema/schema_types.py
tests/loader/test_loader.py
tests/metadater/field/test_field_functions.py

close #767 
- feat
- improve data type inference for padded codes and nullable integers - 0c7d66ef0bcd81667e6230e1762423cb59fd84d3
---
- https://app.asana.com/0/0/1210222506912082

feat: improve data type inference for padded codes and nullable integers

---

demo/splitter_overlap_demo.py
doc_site/content/docs/api/splitter.md
doc_site/content/docs/api/splitter.zh-tw.md
doc_site/content/docs/developer-guide/test-coverage.md
doc_site/content/docs/developer-guide/test-coverage.zh-tw.md
petsard/loader/splitter.py
petsard/operator.py
petsard/status.py
tests/loader/test_splitter.py
tests/test_config.py
tests/test_operator.py

closes #664 
- refactor:
- implement functional programming with overlap control
---
- https://app.asana.com/0/0/1209361065811392

refactor(splitter): implement functional programming with overlap control

---

pyproject.toml

fix(container): update `pyproject.toml` for container building

---

.gitignore
demo/petsard_wheel_downloader.py
doc_site/content/docs/get-started.md
doc_site/content/docs/get-started.zh-tw.md
petsard_installer_plan.md

- feat
- (demo): add dependency groups support to wheel downloader - 673bb4acd65a72ae7d87510a11f10ec5839201e4

feat(demo): add dependency groups support to wheel downloader

---

petsard/exceptions.py
petsard/metadater/__init__.py
petsard/metadater/change_tracker.py
petsard/metadater/metadater.py
petsard/status.py

- refactor
- (status): diagnose and optimize core architecture with memory-safe containers - 6722a1f557723b074f68b9c1b2c18b3ecc00e232
- (status): improve error handling and eliminate code duplication - aae473311245153644f14bf5675d6b01d61dd4ec
- (status): Restructure Status module architecture and simplify core objects - 3aca604542f3a87c3ad987941e31424cea4384ee

refactor(status): Complete Status module overhaul with performance and architecture improvements

---

.github/dependabot.yml
.github/workflows/ai-assisted-development.yml
.github/workflows/image-publish.yml
.github/workflows/pages.yaml
.github/workflows/semantic-release.yml
.github/workflows/test-suite.yml
.github/workflows/trivy-sbom-gen.yml
.github/workflows/trivy-vuln-scan.yml

chore(deps): upgrade SBOM packages and standardize pyproject.toml format
